(function exposeRefsFactory(global) {
  /**
   * @description 收集并缓存页面中常用 DOM 引用，避免重复查询。
   * @returns {object} 各 UI 节点引用集合。
   */
  function createRefs() {
    return {
      loginOverlay: document.getElementById("login-overlay"),
      loginUsername: document.getElementById("login-username"),
      loginPassword: document.getElementById("login-password"),
      loginError: document.getElementById("login-error"),
      btnLogin: document.getElementById("btn-login"),
      userBar: document.getElementById("user-bar"),
      userDisplayName: document.getElementById("user-display-name"),
      userRoleBadge: document.getElementById("user-role-badge"),
      btnUserManage: document.getElementById("btn-user-manage"),
      btnLogout: document.getElementById("btn-logout"),
      userManageDialog: document.getElementById("user-manage-dialog"),
      btnCloseUserDialog: document.getElementById("btn-close-user-dialog"),
      glyphPickerDialog: document.getElementById("glyph-picker-dialog"),
      btnCloseGlyphPicker: document.getElementById("btn-close-glyph-picker"),
      glyphPickerSearch: document.getElementById("glyph-picker-search"),
      glyphPickerList: document.getElementById("glyph-picker-list"),
      newUserUsername: document.getElementById("new-user-username"),
      newUserPassword: document.getElementById("new-user-password"),
      newUserDisplayName: document.getElementById("new-user-display-name"),
      newUserRole: document.getElementById("new-user-role"),
      btnCreateUser: document.getElementById("btn-create-user"),
      userList: document.getElementById("user-list"),
      reviewStatusSection: document.getElementById("review-status-section"),
      reviewStatusDisplay: document.getElementById("review-status-display"),
      toolbarEditControls: document.getElementById("toolbar-edit-controls"),
      toolbarAnnotationControls: document.getElementById(
        "toolbar-annotation-controls",
      ),
      headingAddSection: document.getElementById("heading-add-section"),
      metaForm: document.getElementById("meta-form"),
      tabs: Array.from(document.querySelectorAll(".tab")),
      panes: {
        editor: document.getElementById("tab-editor"),
        article: document.getElementById("tab-article"),
        glyph: document.getElementById("tab-glyph"),
      },
      imageUpload: document.getElementById("image-upload"),
      btnClearPages: document.getElementById("btn-clear-pages"),
      btnPrevPage: document.getElementById("btn-prev-page"),
      btnNextPage: document.getElementById("btn-next-page"),
      headingTitleInput: document.getElementById("heading-title-input"),
      headingDropRootZone: document.getElementById("heading-drop-root-zone"),
      btnAddHeading: document.getElementById("btn-add-heading"),
      headingAddTip: document.getElementById("heading-add-tip"),
      headingIndexList: document.getElementById("heading-index-list"),
      btnZoomOut: document.getElementById("btn-zoom-out"),
      btnZoomReset: document.getElementById("btn-zoom-reset"),
      btnZoomIn: document.getElementById("btn-zoom-in"),
      pageIndicator: document.getElementById("page-indicator"),
      canvasMeta: document.getElementById("canvas-meta"),
      canvasViewport: document.getElementById("canvas-viewport"),
      pageImage: document.getElementById("page-image"),
      canvasStage: document.getElementById("canvas-stage"),
      annotationSvg: document.getElementById("annotation-svg"),
      annotationLevel: document.getElementById("annotation-level"),
      annotationForm: document.getElementById("annotation-form"),
      annotationFormTemplate: document.getElementById(
        "annotation-form-template",
      ),
      annotationList: document.getElementById("annotation-list"),
      btnExportGlyph: document.getElementById("btn-export-glyph"),
      glyphImportFile: document.getElementById("glyph-import-file"),
      glyphCode: document.getElementById("glyph-code"),
      glyphName: document.getElementById("glyph-name"),
      glyphNote: document.getElementById("glyph-note"),
      glyphImage: document.getElementById("glyph-image"),
      btnCaptureGlyph: document.getElementById("btn-capture-glyph"),
      btnClearCapturedGlyph: document.getElementById(
        "btn-clear-captured-glyph",
      ),
      glyphCaptureTip: document.getElementById("glyph-capture-tip"),
      glyphCapturePreviewWrap: document.getElementById(
        "glyph-capture-preview-wrap",
      ),
      glyphCapturePreview: document.getElementById("glyph-capture-preview"),
      btnAddGlyph: document.getElementById("btn-add-glyph"),
      glyphList: document.getElementById("glyph-list"),
      metaArticleId: document.getElementById("meta-article-id"),
      metaTitle: document.getElementById("meta-title"),
      metaSubtitle: document.getElementById("meta-subtitle"),
      metaAuthor: document.getElementById("meta-author"),
      metaBook: document.getElementById("meta-book"),
      metaVolume: document.getElementById("meta-volume"),
      metaPublishYear: document.getElementById("meta-publish-year"),
      metaWritingYear: document.getElementById("meta-writing-year"),
      btnExportXml: document.getElementById("btn-export-xml"),
      articleSelectOverlay: document.getElementById("article-select-overlay"),
      articleGrid: document.getElementById("article-grid"),
      articleCreateSection: document.getElementById("article-create-section"),
      newArticleTitle: document.getElementById("new-article-title"),
      newArticleSubtitle: document.getElementById("new-article-subtitle"),
      newArticleAuthor: document.getElementById("new-article-author"),
      btnCreateArticle: document.getElementById("btn-create-article"),
      btnBackToSelect: document.getElementById("btn-back-to-select"),
      selectUserDisplayName: document.getElementById(
        "select-user-display-name",
      ),
      selectUserRoleBadge: document.getElementById("select-user-role-badge"),
      btnSelectUserManage: document.getElementById("btn-select-user-manage"),
      btnSelectLogout: document.getElementById("btn-select-logout"),
      articleAccessDialog: document.getElementById("article-access-dialog"),
      btnCloseAccessDialog: document.getElementById("btn-close-access-dialog"),
      accessArticleTitle: document.getElementById("access-article-title"),
      accessUserSelect: document.getElementById("access-user-select"),
      btnGrantAccess: document.getElementById("btn-grant-access"),
      accessUserList: document.getElementById("access-user-list"),
      btnAiOcrRegion: document.getElementById("btn-ai-ocr-region"),
    };
  }

  global.createRefs = createRefs;
})(window);
